version: '3'
services:
  app-database:
    image: 10.6.0.243:5000/app-database:latest
    networks:
      - db_internal
    environment:
      - MYSQL_ROOT_PASSWORD=<root_pass>
      - MYSQL_DATABASE=customerdb
      - MYSQL_USER=<db_user>
      - MYSQL_PASSWORD=<db_pass>
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306 
  app-backend:
    image: 10.6.0.243:5000/backend-api:latest
    networks:
      - app_external
      - db_internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://app-database:3306/customerdb
      - SPRING_DATASOURCE_USERNAME=<db_user>
      - SPRING_DATASOURCE_PASSWORD=<db_pass>
      - CROS_ALLOWED_ORIGINS=http://<serverIP>:8081
    ports:
      - 8080:8080
    depends_on:
      app-database:
       condition: service_healthy
  app-frontend:
    image: 10.6.0.243:5000/frontend-api:latest
    networks:
      - app_external
    ports:
      - 8081:8081
    depends_on:
      - app-backend

volumes:
  database:
networks:
 db_internal:
 app_external:
