version: '3'
services:
  app-database:
    image: 10.6.0.243:5000/app-database:latest
    environment:
      - MYSQL_ROOT_PASSWORD=<root_pass>
      - MYSQL_DATABASE=customerdb
      - MYSQL_USER=<db_user>
      - MYSQL_PASSWORD=<db_pass>
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 3
  app-backend:
    image: 10.6.0.243:5000/backend-api:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://app-database:3306/customerdb
      - SPRING_DATASOURCE_USERNAME=<db_user>
      - SPRING_DATASOURCE_PASSWORD=<db_pass>
      - SPRING_MVC_CROS_ALLOWED-ORIGINS=http://<serverIP>:8081
    ports:
      - 8080:8080
    depends_on:
      - app-database
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 30s
  app-frontend:
    image: 10.6.0.243:5000/frontend-api:latest
    environment:
      - API_BASE_URL=http://<serverURL>:8080
    ports:
      - 8081:8081
    depends_on:
      - app-backend
      - app-database
volumes:
  database:

